from datetime import time

SYMBOL_CANONICAL = "GU"
SYMBOL_VARIANTS = ("GBPUSD", "GBPUSDm", "GBPUSD.r")

PIP_SIZE = 0.0001
LIQUIDITY_SWEEP_PIPS = 1

POLL_SECONDS = 60
CANDLE_COUNT = 300

SWING_LEFT = 2
SWING_RIGHT = 2
SWING_LEFT_4H = 4
SWING_RIGHT_4H = 4

BROKER_UTC_OFFSET_HOURS = 0

LONDON_START_UTC = time(7, 0)
LONDON_END_UTC = time(11, 0)

NY_ENABLED = True
NY_START_UTC = time(12, 0)
NY_END_UTC = time(14, 0)

USE_1M_ENTRY = True
REQUIRE_1M_CHOCH_PREMIUM = True
REQUIRE_5M_CHOCH_PREMIUM = True
ENABLE_1M_ENTRY_SELL = False
REQUIRE_5M_CHOCH_PREMIUM_SELL = False

PREMIUM_CROSS_LEVEL = 0.7
DISCOUNT_CROSS_LEVEL = 0.3

ENABLE_SPREAD_FILTER = False
MAX_SPREAD_PIPS = 2.0
ASSUME_ZERO_SPREAD = True
SL_EXTRA_PIPS = 3.0
ENABLE_BREAK_EVEN = False
REQUIRE_NO_LIQUIDITY_SWEEP = False
REQUIRE_LIQUIDITY_SWEEP_SELL = False

ENABLE_CHOCH_RANGE_FILTER = False
MIN_CHOCH_RANGE_PIPS = 6.0

ENABLE_RISK_MANAGEMENT = True
RISK_PER_TRADE_PCT = 1.0
ACCOUNT_BALANCE_OVERRIDE = 10000.0
PIP_VALUE_PER_LOT = 10.0
MIN_LOT_SIZE = 0.01
MAX_LOT_SIZE = 5.0
LOT_STEP = 0.01
